# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single unfolded result.
# One can also specify a list of jetR, which will be looped over.
#
# The process step is intended  to loop over all observables simultaneously
# The analysis step is intended to run for a single observable block

process_observables: ['theta_g', 'zg', 'subjet_z', 'jet_axis']
jetR: [0.2, 0.3, 0.4]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
mc_fraction_threshold: 0.5
reject_tracks_fraction: 0.0
debug_level: 0

constituent_subtractor:
  max_distance: 0.25
  alpha: 0
  max_eta: 0.9
  bge_rho_grid_size: 1.0
  max_pt_correct: 100
  ghost_area: 0.01

emb_file_list: '/rstorage/alice/data/LHC18qr/147-148/files.txt'

# Observable block
theta_g:

  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80,  90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 5
      
  config2:
    SoftDrop:
      zcut: 0.2
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 5
      
  config3:
    SoftDrop:
      zcut: 0.3
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 5
      
  config4:
    DynamicalGrooming:
      a: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 5
      
  config5:
    DynamicalGrooming:
      a: 1.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 5
      
  config6:
    DynamicalGrooming:
      a: 2.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 5

# Observable block
zg:

  config1:
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0.1, 0.13, 0.16, 0.19, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    obs_bins_det_sys_binning: [0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    reg_param:
      0.4: 3
      
  config2:
    SoftDrop:
      zcut: 0.2
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    obs_bins_det_sys_binning: [0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    reg_param:
      0.4: 3
      
  config3:
    SoftDrop:
      zcut: 0.3
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0.3, 0.33, 0.36, 0.39, 0.42, 0.45, 0.5]
    obs_bins_det_sys_binning: [0.3, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    reg_param:
      0.4: 3
      
  config4:
    DynamicalGrooming:
      a: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0., 0.05, 0.1, 0.13, 0.16, 0.19, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    reg_param:
      0.4: 5
      
  config5:
    DynamicalGrooming:
      a: 1.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0., 0.05, 0.1, 0.13, 0.16, 0.19, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    reg_param:
      0.4: 5
      
  config6:
    DynamicalGrooming:
      a: 2.0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]
    obs_bins_det: [0., 0.05, 0.1, 0.13, 0.16, 0.19, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    obs_bins_det_sys_binning: [0., 0.05, 0.1, 0.12, 0.14, 0.16, 0.18, 0.2, 0.22, 0.25, 0.28, 0.31, 0.34, 0.37, 0.4, 0.43, 0.46, 0.5]
    reg_param:
      0.4: 5

# Observable block
subjet_z:

  config1:
    subjet_R: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 0.9, 0.95, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 3
    
  config2:
    subjet_R: 0.2
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 120, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 0.9, 0.95, 1.0]
    obs_bins_det: [0., 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.55, 0.6, 0.65, 0.7, 0.8, 0.9, 1.0]
    obs_bins_det_sys_binning: [0., 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 1.0]
    reg_param:
      0.4: 3
  
# Observable block
jet_axis:

  config1:
    axis: 'Standard_WTA'
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.02, 0.05, 0.1, 0.15, 0.2, 0.4]
    obs_bins_det: [0., 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    obs_bins_det_sys_binning: [0., 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    reg_param:
      0.4: 3
      
  config2:
    axis: 'Standard_SD'
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.02, 0.05, 0.1, 0.15, 0.2, 0.4]
    obs_bins_det: [0., 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    obs_bins_det_sys_binning: [0., 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    reg_param:
      0.4: 3
      
  config3:
    axis: 'WTA_SD'
    SoftDrop:
      zcut: 0.1
      beta: 0
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [35, 40, 45, 50, 55, 60, 70, 80, 90, 100, 120]
    pt_bins_det_sys_truncation: [7, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.02, 0.05, 0.1, 0.15, 0.2, 0.4]
    obs_bins_det: [0., 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    obs_bins_det_sys_binning: [0., 0.005, 0.01, 0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
    reg_param:
      0.4: 3

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/Users/jamesmulligan/Analysis_theta_g/roounfold_rg_output_41084'
roounfold_path: '/Users/jamesmulligan/RooUnfold/build/libRooUnfold.dylib'

analysis_observable: 'subjet_z'
do_unfolding: False
force_rebin: False
do_systematics: False
do_plot_final_result: False
do_plot_performance: True

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  
# Prior variation parameters
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5

# Paths to processing output, to be used for unfolding
main_data: '/Users/jamesmulligan/Analysis_theta_g/AnalysisResults/LHC17pq/40593/AnalysisResultsFinal.root'
main_response: '/Users/jamesmulligan/Analysis_theta_g/AnalysisResults/LHC18b8/40664/AnalysisResultsFinal.root'
trkeff_response: '/Users/jamesmulligan/Analysis_theta_g/AnalysisResults/LHC18b8_trkeff/40972/AnalysisResultsFinal.root'

# Theory comparisons
fPythia: '/Users/jamesmulligan/Analysis_theta_g/Pythia_new/pythia.root'

fNLL: ''
fNPcorrection_numerator: '/Users/jamesmulligan/Analysis_theta_g/NP_correction/Full_hadON_mpiON_isrON/default_output.root'
fNPcorrection_denominator: '/Users/jamesmulligan/Analysis_theta_g/NP_correction/Full_hadOFF_mpiOFF_isrOFF/default_output.root'
