# Configuration for:
#   (a) Processing of ROOT trees into histograms
#   (b) Analysis of histograms into final result
#
# The observables are structured into observable blocks (e.g. theta_g, subjet_z, etc.)
# each containing multiple individual subconfigurations (e.g. zcut, beta, subjetR, etc.),
# where each subconfiguration corresponds to a single unfolded result.
# One can also specify a list of jetR, which will be looped over.
#
# The process step is intended to loop over all observables simultaneously
# The analysis step is intended to run for a single observable block

process_observables: ['inclusive_subjet_z', 'leading_subjet_z']
jetR: [0.2]
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0.0
eta_max: 0.9
debug_level: 0
dry_run: False
fast_simulation: False

# Observable block
inclusive_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{N}_{subjets}} #frac{d#it{N}}{d#it{z_{r}}}'
    pt_bins_reported: [60, 80]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   z-truth: 0.02
  #   z-det: 0.01

  config1:
    subjet_R: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.06, 0.12, 0.18, 0.24, 0.34, 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det: [0., 0.06, 0.12, 0.18, 0.24, 0.34, 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det_sys_binning: [0., 0.01, 0.02, 0.03, 0.04, 0.06, 0.12, 0.18, 0.24, 0.3, 0.36, 0.42, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]

# Observable block
leading_subjet_z:

  common_settings:
    xtitle: '#it{z_{r}}'
    ytitle: '#frac{1}{#it{N}_{jets}} #frac{d#it{N}}{d#it{z_{r}}}'
    pt_bins_reported: [60, 80]
    max_reg_param: 10
    plot_overlay_list:
      - ['config1']
      
  # RM binnings from processing:
  #   pt-truth: 10 GeV
  #   pt-det: 5 GeV
  #   z-truth: 0.02
  #   z-det: 0.01

  config1:
    subjet_R: 0.1
    pt_bins_truth: [5, 20, 40, 60, 80, 100, 150, 300]
    pt_bins_det: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 80]
    pt_bins_det_sys_truncation: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 70, 85]
    obs_bins_truth: [0., 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det: [0., 0.5, 0.66, 0.76, 0.82, 0.88, 0.94, 1.0]
    obs_bins_det_sys_binning: [0., 0.1, 0.2, 0.3, 0.4, 0.48, 0.54, 0.6, 0.66, 0.72, 0.8, 0.9, 0.96, 0.98, 0.99, 1.0]

###############################################################################
# Analysis parameters

file_format: '.pdf'
output_dir: '/Users/jamesmulligan/Analysis_subjet_z/output_analysis/pp/432533-02'
roounfold_path: '/Users/jamesmulligan/heppy/external/roounfold/roounfold-current/lib/libRooUnfold.dylib'

analysis_observable: 'inclusive_subjet_z'
do_unfolding: True
force_rebin: True
do_systematics: True
do_plot_final_result: True
do_plot_performance: True
figure_approval_status: 'Prel. candidate'

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - fastsim_generator0
  - fastsim_generator1

# Paths to processing output, to be used for unfolding
main_data: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC17pq/432533/AnalysisResultsFinal.root'
main_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8/432534/AnalysisResultsFinal.root'
trkeff_response: '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_trkeff/432535/AnalysisResultsFinal.root'
fastsim_response:
 - '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_fastsim_pythia/432536/AnalysisResultsFinal.root'
 - '/Users/jamesmulligan/Analysis_subjet_z/output_process/LHC18b8_fastsim_herwig/432537/AnalysisResultsFinal.root'

# Prior variation parameters
prior_variation_option: 0
prior1_variation_parameter: 1.
prior2_variation_parameter: -1.
