# Processing parameters
jetR: [0.4]
betas: [1, 1.5, 2, 3]

# Initial detector-level binnings. Distributions are rebinned via configs before unfolding
n_pt_bins: 195
pt_limits: [5, 200]
n_lambda_bins: 160
lambda_limits: [0, 0.8]
n_rap_bins: 20            # just for fun, look at lambda distribution vs rapidity
rap_limits: [-0.5, 0.5]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['ang']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

# SoftDrop setting (current same for all SD plots)
sd_zcut: 0.1    # multiplier
sd_beta: 0      # exponent on (deltaR / R)


###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
ang:

  common_settings:
    xtitle: '#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}'
    ytitle: '#frac{1}{#it{#sigma}_{jet}} #frac{d#it{#sigma}}{d#it{#lambda}_{#it{#beta}}^{#it{#kappa}=1}}'
    pt_bins_reported: [60, 80]
    plot_overlay_list:
      - ['config_R0.4_B1', 'config_R0.4_B1.5', 'config_R0.4_B2', 'config_R0.4_B3']
      - ['config_R0.4_B1_SD', 'config_R0.4_B1.5_SD', 'config_R0.4_B2_SD', 'config_R0.4_B3_SD']
    max_reg_param: 10

  ############################################################################
  # Different R & beta configurations
  config_R0.4_B1:
    R: 0.4
    beta: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.05, 0.1, 0.15, 0.25, 0.35, 0.55, 0.75]
    obs_max_reported: [0.55]
    obs_bins_det: [0, 0.06, 0.09, 0.12, 0.17, 0.25, 0.35, 0.55, 0.75]
    obs_bins_det_sys_binning: [0, 0.05, 0.1, 0.13, 0.17, 0.21, 0.3, 0.41, 0.6, 0.75]

  config_R0.4_B1.5:
    R: 0.4
    beta: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.03, 0.07, 0.12, 0.16, 0.2, 0.25, 0.45, 0.6]
    obs_max_reported: [0.45]
    obs_bins_det: [0, 0.03, 0.05, 0.07, 0.12, 0.16, 0.20, 0.25, 0.45, 0.6]
    obs_bins_det_sys_binning: [0, 0.03, 0.045, 0.075, 0.09, 0.125, 0.155, 0.21, 0.26, 0.32, 0.48, 0.6]

  config_R0.4_B2:
    R: 0.4
    beta: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.03, 0.06, 0.1, 0.15, 0.20, 0.35, 0.5]
    obs_max_reported: [0.35]
    obs_bins_det: [0, 0.03, 0.06, 0.1, 0.15, 0.20, 0.35, 0.5]
    obs_bins_det_sys_binning: [0, 0.02, 0.055, 0.085, 0.13, 0.16, 0.22, 0.37, 0.45]

  config_R0.4_B3:
    R: 0.4
    beta: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.01, 0.02, 0.04, 0.06, 0.11, 0.25, 0.4]
    obs_max_reported: [0.25]
    obs_bins_det: [0, 0.01, 0.02, 0.04, 0.06, 0.11, 0.25, 0.4]
    obs_bins_det_sys_binning: [0, 0.01, 0.025, 0.045, 0.065, 0.105, 0.23, 0.35]

  ############################################################################
  # Different R & beta configurations for SoftDrop
  config_R0.4_B1_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 1
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.03, 0.05, 0.07, 0.1, 0.15, 0.25, 0.4, 0.6, 0.8]
    obs_max_reported: [0.6]
    obs_bins_det: [0, 0.02, 0.04, 0.06, 0.09, 0.17, 0.25, 0.4, 0.6, 0.8]
    obs_bins_det_sys_binning: [0, 0.015, 0.03, 0.05, 0.1, 0.15, 0.25, 0.41, 0.58, 0.8]
    reg_param:
      0.4: 3

  config_R0.4_B1.5_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 1.5
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.01, 0.02, 0.05, 0.1, 0.15, 0.25, 0.5, 0.7]
    obs_max_reported: [0.5]
    obs_bins_det: [0, 0.01, 0.02, 0.04, 0.06, 0.1, 0.15, 0.25, 0.5, 0.7]
    obs_bins_det_sys_binning: [0, 0.015, 0.03, 0.045, 0.06, 0.1, 0.12, 0.155, 0.26, 0.58, 0.7]
    reg_param:
      0.4: 3

  config_R0.4_B2_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 2
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.01, 0.02, 0.04, 0.08, 0.15, 0.35, 0.6]
    obs_max_reported: [0.35]
    obs_bins_det: [0, 0.005, 0.01, 0.02, 0.045, 0.07, 0.1, 0.15, 0.2, 0.35, 0.6]
    obs_bins_det_sys_binning: [0, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.155, 0.21, 0.33, 0.6]
    reg_param:
      0.4: 3

  config_R0.4_B3_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    R: 0.4
    beta: 3
    pt_bins_truth:  [5, 20, 40, 60, 80, 100, 150, 200]
    pt_bins_det: [5, 10, 15, 20, 25, 30, 40, 50, 60, 80, 100, 120, 150, 200]
    pt_bins_det_sys_truncation: [10, 15, 20, 25, 30, 40, 50, 60, 80, 100]
    obs_bins_truth: [0, 0.01, 0.02, 0.05, 0.1, 0.25, 0.5]
    obs_max_reported: [0.25]
    obs_bins_det: [0, 0.005, 0.015, 0.03, 0.06, 0.1, 0.25, 0.5]
    obs_bins_det_sys_binning: [0, 0.005, 0.015, 0.035, 0.07, 0.11, 0.24, 0.5]
    reg_param:
      0.4: 3


###############################################################################
# Theory comparison parameters
do_theory_comp: False
theory_beta: [1.5, 2, 3]
theory_dir: "/home/ezra/ALICE_table/"
theory_pt_bins: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]
response_files: ["/rstorage/alice/AnalysisResults/ang/196181/AnalysisResultsFinal.root",
                 "/rstorage/alice/AnalysisResults/ang/225271/AnalysisResultsFinal.root"]
response_labels: ["PYTHIA8", "Herwig7"]
rebin_theory_response: False


###############################################################################
# Analysis & plotting parameters
file_format: ".pdf"
output_dir: "/rstorage/alice/AnalysisResults/ang/AngR04_ptbin3"
roounfold_path: "/home/ezra/heppy/external/roounfold/roounfold-2.0.0/lib/libRooUnfold.so"

analysis_observable: 'ang'
do_unfolding: True
force_rebin: True
do_systematics: True
do_plot_final_result: True
do_plot_performance: False
figure_approval_status: 'Preliminary'

# Whether or not to use the previous preliminary result in final results
use_prev_prelim: False

# List of which systematics to perform
# Options: [main, trkeff, prior1, prior2, truncation, binning, \
#           random_mass, fastsim_generator0, fastsim_generator1]
systematics_list:
  - main
  - trkeff
  - prior1
  - prior2
  - truncation
  - binning
  - random_mass
  - fastsim_generator0
  - fastsim_generator1

# Paths to processing output, to be used for unfolding
main_data: '/rstorage/alice/AnalysisResults/ang/277053/AnalysisResultsFinal.root'
main_response: '/rstorage/alice/AnalysisResults/ang/277214/AnalysisResultsFinal.root'
trkeff_response: '/rstorage/alice/AnalysisResults/ang/277215/AnalysisResultsFinal.root'
randmass_data: '/rstorage/alice/AnalysisResults/ang/277216/AnalysisResultsFinal.root'
randmass_response: '/rstorage/alice/AnalysisResults/ang/277217/AnalysisResultsFinal.root'
fastsim_response: ['/rstorage/alice/AnalysisResults/ang/281633/AnalysisResultsFinal.root',
                   '/rstorage/alice/AnalysisResults/ang/281794/AnalysisResultsFinal.root']

# Prior variation parameters
prior_variation_option: 1
prior1_variation_parameter: 0.5
prior2_variation_parameter: -0.5
