# Processing parameters
jetR: [0.2, 0.4]
betas: [1.5, 2, 3]

# Initial detector-level binnings. Distributions are rebinned via configs before unfolding
n_pt_bins: 195
pt_limits: [5, 200]
n_lambda_bins: 160
lambda_limits: [0, 0.8]
n_rap_bins: 50            # just for fun, look at lambda distribution vs rapidity
rap_limits: [-1, 1]

# For extra verbose output in some functions
debug_level: 0

process_observables: ['ang']
jet_matching_distance: 0.6        # Match jets with deltaR < jet_matching_distance*jetR
reject_tracks_fraction: 0

# SoftDrop setting (current same for all SD plots)
sd_zcut: 0.2    # multiplier
sd_beta: 0      # exponent on (deltaR / R)

response_levels: [["p", "ch", "off"], ["p", "h", "off"], ["h", "ch", "on"]]
theory_pt_bins: [10, 15, 20, 25, 30, 35, 40, 45, 50, 60, 70, 80, 90, 100,
                 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]


###############################################################################
# Rebinning and unfolding parameters/configurations for angularity observables
ang:

  ############################################################################
  # Different R & beta configurations

  config_B1.5:
    beta: 1.5

  config_B2:
    beta: 2

  config_B3:
    beta: 3

  ############################################################################
  # Different R & beta configurations for SoftDrop

  config_B1.5_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 1.5

  config_B2_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 2

  config_B3_SD:
    SoftDrop:
      zcut: 0.2
      beta: 0
    beta: 3